DB/DB-20-Social_media_project/simplesocial/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

DB/DB-20-Social_media_project/simplesocial/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<pk>/', views.DeletePost.as_view(), name='delete')
]

DB/DB-20-Social_media_project/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

DB/DB-20-Social_media_project/simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>

    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" rel="stylesheet">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link href="{% static 'simplesocial/css/master.css' %}" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark mynav" id="navbar" role="navigation">
    <div class="container">
        <div class="navbar-nav align-items-center">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        </div>
        <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li><a class="nav-item nav-link" href="{% url 'posts:create' %}">Post</a></li>
                <li><a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                <li><a class="nav-item nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
                <li><a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li><a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                <li><a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container mycontent">


    {% block content %}

    {% endblock %}
</div>

<canvas id="canvas"></canvas>

<script simplesocial src="{% static "/js/master.js" %}" type="text/javascript"></script>

<!-- Latest compiled and minified jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script crossorigin="anonymous" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


</body>
<script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}">
</script>
</html>

DB/DB-20-Social_media_project/simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>

{% endblock %}

DB/DB-20-Social_media_project/simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
    <h1>You are now logged in!</h1>

{% endblock %}

DB/DB-20-Social_media_project/simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
    <h1>Thanks mon for visit'n, come back!</h1>

{% endblock %}